### ISSUE TITLE
Updates to TeX and LaTeX Books

### ISSUE THREAD

**Issue by schneeschmelze** [latex3/latex3.github.io#12]
I just would like to draw your attention to two books on the list at <https://www.latex-project.org/help/books/> resp. <https://github.com/latex3/latex3.github.io/blob/main/help/books/index.md> that need an update. I'm not sure whether it's the right way to open an issue for this or whether to fork the said page on GitHub and ask for a merge which I also have not done before.

First, Joachim Schlosser's introduction to LaTeX was last published in 2021, 7th&nbsp;ed., ISBN 9783747504468. DNB catalogue data is available from <https://d-nb.info/1239381263>. The URL to the publisher's website is: <https://www.mitp.de/IT-Web/Studium/Wissenschaftliche-Arbeiten-schreiben-mit-LaTeX.html>.

Then, the URL for the open access book by Alexander Borbon A., Walter Mora F. in Spanish is no longer valid. However, there is a 2022 edition available which can be found at <https://tecdigital.tec.ac.cr/servicios/revistamatematica/Libros/LaTeX/>. It seems it is still the second edition, although it bears a 2022 on its cover and the landing page is titled 2020.

Thanks for looking into this.

**Comment by FrankMittelbach** [comment]
thanks. Not easy to keep up with such changes ... I updated the sources but have not yet uploaded them, because of some other pending changes.

Pull requests for simpler fixes may make my life easier, but  already for this case I'm not sure. If you make a pull request, you have to make it against the main branch.
